### ISSUE TITLE
Any way to check the side?

### ISSUE THREAD

**Issue by Soulbadguy54** [StuartTheYellowOne/async_faceit_api#1]
Hello! Is there any way to check who started on ct or t side in the finished match?

Looks like any api answer does not contain this field

**Comment by StuartTheYellowOne** [comment]
Hey, it seems to be a limitation of the Faceit v4 API :/
I only see 2 possible solutions:
- Download the demo and analyse the transcription. The demo download link is in a match object. ( I might add this functionality in the function)
- Use webhooks and listen for a changed match status
I searched the (Faceit for Developers)[https://discord.gg/zvJcbMxF] Discord server for this topic, but only found these 2 ideas. But you might ask them as well.

**Comment by Soulbadguy54** [comment]
> Hey, it seems to be a limitation of the Faceit v4 API :/ I only see 2 possible solutions:
> 
> * Download the demo and analyse the transcription. The demo download link is in a match object. ( I might add this functionality in the function)
> * Use webhooks and listen for a changed match status
>   I searched the (Faceit for Developers)[https://discord.gg/zvJcbMxF] Discord server for this topic, but only found these 2 ideas. But you might ask them as well.

Thx. The 1st solution is hard, since faceit block the access to download API T_T
