### ISSUE TITLE
Aiohttp 3.8.3 and python 3.12

### ISSUE THREAD

**Issue by Soulbadguy54** [StuartTheYellowOne/async_faceit_api#2]
Is there any crucial changes in newer versions of aiohttp, which could brake this library?

I want to use python 3.12 since other library wrote only for python 3.12, but cant upgrade till aiohttp 3.8.3 not allowed at this python version. The thing i want to do is simple install async faceit apy public branch without requirements and use new versions of python and aiohttp. Will it brake my project? 

Thx for your time again :)

**Comment by StuartTheYellowOne** [comment]
I think there is no problem with upgrading the aiohttp package to the
version you need. Im not aware of any breaking changes in aiohttp.

Am Mo., 13. Mai 2024 um 19:58 Uhr schrieb Soulbadguy54 <
***@***.***>:

**Comment by Soulbadguy54** [comment]
Yes! Its working perfect. I think you could upgrade the package in pypi with 3.12 python compability :) Thx you for your work
